"""
Django settings for e_voting project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n9-!c)#uc5z#(upiry9v9#-$#=f*0fw0o^a9254j=oaqgu(+v5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'e_voting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'e_voting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL='login_view'

MEDIA_URL = 'media/'

# settings.py

JAZZMIN_SETTINGS = {
    # General Settings
    "site_title": "Rongo University Admin",
    "site_header": "Rongo University",
    "site_brand": "Rongo Voting System",
    "site_logo": "images/logo.png",
    "welcome_sign": "Rongo University Voting Administration",
    "copyright": "© 2023 Rongo University",
    
    # Theme Configuration
    "theme": "lux",  # Best built-in theme for gold/white/blue
    "dark_mode_theme": None,  # Disable dark mode for consistency
    
    # Color Customization
    "custom_css": None,  # No custom CSS
    "custom_js": None,
    
    # UI Tweaks
    "show_ui_builder": True,
    "navigation_expanded": True,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
    
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
        {"name": "Support", "url": "mailto:support@rongo.ac.ke", "new_window": True},
    ],
    
    # Icons (Gold-themed)
    "icons": {
        "auth.User": "fas fa-user-graduate",
        "auth.Group": "fas fa-users-cog",
        "voting.Election": "fas fa-vote-yea",
        "voting.Position": "fas fa-award",
        "voting.Candidate": "fas fa-user-tie",
        "voting.Voter": "fas fa-user-check",
        "voting.Vote": "fas fa-check-circle",
        "sites.Site": "fas fa-globe-africa",
    },
    
    # Menu Ordering
    "order_with_respect_to": [
        "voting",
        "voting.Election",
        "voting.Position",
        "voting.Candidate",
        "voting.Voter",
        "voting.Vote",
        "auth",
    ],
    
    # Authentication UI
    "login_logo": "images/logo.png",
    "login_bg_color": "linear-gradient(135deg, #003366 0%, #001a33 100%)",
    "login_box_bg_color": "#FFFFFF",
    "login_box_border_color": "#FFD700",
    "login_box_radius": 10,
}

JAZZMIN_UI_TWEAKS = {
    # Color Palette
    "theme": "lux",
    "primary": "#003366",  # Rongo Blue
    "secondary": "#FFD700",  # Rongo Gold
    "info": "#17a2b8",
    "warning": "#f39c12",
    "danger": "#dc3545",
    "success": "#28a745",
    
    # Layout
    "navbar": "navbar-white navbar-light",
    "navbar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,
    
    # Header
    "navbar_brand_color": "text-dark",
    "navbar_logo_bg_color": None,
    
    # Sidebar
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "sidebar_nav_compact_style": False,
    "sidebar_disable_expand": False,
    
    # Cards
    "card": {
        "outline": False,
        "header_bg": "#003366",
        "header_color": "white",
        "header_border_bottom": "#FFD700",
    },
    
    # Buttons
    "button_classes": {
        "primary": "btn btn-primary",
        "secondary": "btn btn-secondary",
        "info": "btn btn-info",
        "warning": "btn btn-warning",
        "danger": "btn btn-danger",
        "success": "btn btn-success"
    },
    
    # Tables
    "table": {
        "header_bg": "#003366",
        "header_color": "white",
        "striped_bg": "rgba(0, 51, 102, 0.05)",
    },
    
    # Misc
    "actions_sticky_top": True,
    "show_sidebar": True,
    "related_modal_active": True,
}