# Generated by Django 5.2.1 on 2025-09-05 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='base_electi_start_d_dcf014_idx'), models.Index(fields=['is_active'], name='base_electi_is_acti_5cec43_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('max_votes', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='base.election')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('manifesto', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('party', models.CharField(blank=True, max_length=100)),
                ('course_year', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='base.position')),
            ],
        ),
        migrations.CreateModel(
            name='ResultDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_type', models.CharField(choices=[('pdf', 'PDF Report'), ('excel', 'Excel Data'), ('summary', 'Executive Summary')], max_length=10)),
                ('file', models.FileField(upload_to='results/downloads/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='base.election')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254700000000'.", regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(blank=True, max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('election_reminders', models.BooleanField(default=True)),
                ('results_announcements', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_abstained', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Review'), ('disputed', 'Disputed')], default='verified', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='base.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='base.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='base.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='base.voter')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CandidateStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('votes', 'Votes'), ('approval', 'Approval Rating'), ('views', 'Profile Views')], max_length=50)),
                ('value', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='base.candidate')),
            ],
            options={
                'indexes': [models.Index(fields=['candidate', 'stat_type'], name='base_candid_candida_a23222_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_voters', models.PositiveIntegerField(default=0)),
                ('votes_cast', models.PositiveIntegerField(default=0)),
                ('voter_turnout', models.FloatField(default=0)),
                ('faculty_data', models.JSONField(default=dict)),
                ('timeline_data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='base.election')),
            ],
            options={
                'indexes': [models.Index(fields=['election'], name='base_electi_electio_df9597_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectionTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('icon', models.CharField(default='fas fa-calendar-alt', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='base.election')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['election', 'event_date'], name='base_electi_electio_f252b0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['election', 'order'], name='base_positi_electio_6cf4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['position', 'is_approved'], name='base_candid_positio_3298f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('user', 'position')},
        ),
        migrations.AddIndex(
            model_name='resultdownload',
            index=models.Index(fields=['election', 'download_type'], name='base_result_electio_90ed97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultdownload',
            unique_together={('election', 'download_type')},
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['student_id', 'is_verified'], name='base_voter_student_a2f2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter', 'election'], name='base_vote_voter_i_aa5c14_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['candidate', 'election'], name='base_vote_candida_55d0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['timestamp'], name='base_vote_timesta_c5e669_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'position', 'election')},
        ),
    ]
