# Generated by Django 5.2.1 on 2025-09-05 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('registration_format', models.CharField(help_text='Regex pattern for validating student IDs', max_length=200)),
                ('color', models.CharField(default='#003366', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='block_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_verified_on_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='base.school'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.school'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['school'], name='base_candid_school__175610_idx'),
        ),
    ]
