# Generated by Django 5.2.1 on 2025-05-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='position',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_abstained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.election'),
        ),
    ]
