# Generated by Django 5.2.1 on 2025-09-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_school_vote_block_number_vote_is_verified_on_chain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='code',
        ),
    ]
