# Generated by Django 5.2.1 on 2025-05-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_candidate_approval_rating_candidate_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='_votes_count',
            field=models.PositiveIntegerField(db_column='votes_count', default=0),
        ),
    ]
